- name: systemd stop logstash 
  systemd:
    state: stopped 
    name: "logstash"
- name: systemd stop {{ app_name }} 
  systemd:
    state: stopped 
    name: "{{ app_name }}"
- name: copy latest binary
  copy: 
    src: "{{ cache_dir }}/{{ app_name }}"
    dest: "{{ binary_dir }}/{{ app_name }}"
    remote_src: yes
    owner: "{{ user }}"
    mode: 0755
- name: read systemd config changes
  systemd:
    daemon_reload: yes
- name: systemd start {{ app_name }}
  systemd:
    state: started 
    name: "{{ app_name }}"
- name: systemd start logstash 
  systemd:
    state: started 
    name: "logstash"
