- name: copy latest binary
  copy:
    src: "{{ cache_dir }}/{{ app_name }}"
    dest: "{{ binary_dir }}/{{ app_name }}"
    remote_src: yes
    owner: "{{ user }}"
    mode: 0755
- name: read systemd config changes
  systemd:
    daemon_reload: yes
- name: systemd start {{ app_name }}
  systemd:
    state: restarted
    name: "{{ app_name }}"
