- name: Copy {{ app_name }} systemd configuration
  template:
    src: "substrate.service.j2"
    dest: /etc/systemd/system/{{ app_name }}.service 
    owner: root
    group: root
    mode: 0600
  register: systemd_updated
- name: create /var/log/{{ app_name }}
  file:
    path: "/var/log/{{ app_name }}"
    state: directory
- name: systemd stop logstash
  systemd:
    state: stopped
    name: "logstash"
  when: systemd_updated.changed
- name: enable {{ app_name }}  service 
  service:
    name: "{{ app_name }}"
    enabled: yes
- name: Start {{ app_name }} service 
  systemd:
    name: "{{ app_name }}"
    state: started
- name: read systemd config changes
  systemd:
    daemon_reload: yes
  when: systemd_updated.changed
- name: systemd start "{{ app_name }}"
  systemd:
    state: restarted 
    name: "{{ app_name }}"
  when: systemd_updated.changed
- name: systemd start logstash
  systemd:
    state: started
    name: "logstash"
  when: systemd_updated.changed
